### PR TITLE
Bump minimum Rust version

### PR DESCRIPTION
**Pull request by haritowa**
Fix for the #505 issue

### CODE REVIEW

**Review by Mirko-von-Leipzig — CHANGES_REQUESTED** [review]
I think technically its version `1.62.0` - could you change it to that?
 Source: https://doc.rust-lang.org/std/primitive.bool.html#method.then_some.

Thanks for the quick PR fix!

**Review by koivunej — CHANGES_REQUESTED** [review]
There's also `crates/pathfinder/Cargo.toml` which has `rust-version = "1.58"`, otherwise thanks for spotting this.

Tested that 1.62.0 is the required.

**Comment by haritowa** [comment]
@Mirko-von-Leipzig @koivunej done

**Review by Mirko-von-Leipzig — APPROVED** [review]
Thanks again! 

FYI the CI test failures are expected -- its because github does not allow external PRs access to our secrets, which causes those ethereum tests to fail.

**Pull request merged**
