### PR TITLE
feat: ecdsa verification

### PR DESCRIPTION
**Pull request by mikdk**
ECDSA verification with temporary sqrt.

### CODE REVIEW

**Review by kkovaacs — APPROVED** [review]
Can't really comment on the math / crypto bits but this seems to be a good hack around ff's lack of sqrt().

**Review by Mirko-von-Leipzig — APPROVED** [review]

**Comment by Mirko-von-Leipzig** [comment]
I guess we should merge?

**Comment by kkovaacs** [comment]
Not yet. I'm not sure this is the most up-to-date version Michael has.

**Comment by kkovaacs** [comment]
@Michael is this PR up-to-date with your latest ECDSA code?

**Comment by kkovaacs** [comment]
This is obsolete now that the more complete refactor PR has been merged.

**Pull request closed without merging**
