### PR TITLE
chore(docs): fix typos

### PR DESCRIPTION
**Pull request by omahs**
Fix: typos

### CODE REVIEW

**Review by Mirko-von-Leipzig — APPROVED** [review]
Firstly, thanks for this.

And then out of curiousity - are you just spell checking all the web3 node projet readmes? In one I notice you mention you're not dev so I'm just wondering about the motivation :D

**Comment by omahs** [comment]
Hey, that's my way of contributing :D
I'm interested in open source and I get to learn about new projects & upcoming features

**Review by sergey-melnychuk — CHANGES_REQUESTED** [review]
Hi @omahs , thank you for fixing the typos!

Please squash commits into one and change title to "chore(docs): fix typos", then we merge it.

**Comment by omahs** [comment]
Hey @sergey-melnychuk I just updated the PR

**Review by sergey-melnychuk — APPROVED** [review]

**Comment by sergey-melnychuk** [comment]
@omahs one last thing and we're good to merge: please change the commit message to "chore(docs): fix typos" (to match the PR title), as we don't do squash & merge but rather rebase on merge.

**Comment by Mirko-von-Leipzig** [comment]
> Hey, that's my way of contributing :D I'm interested in open source and I get to learn about new projects & upcoming features

Great, thanks again. Feel free to reach out if you have questions.

**Pull request merged**
