### PR TITLE
ci: make sure the snippet does not pick the .d file

### PR DESCRIPTION
**Pull request by CHr15F0x**

### CODE REVIEW

**Comment by kkovaacs** [comment]
Slightly unrelated question: why do we need the `.d` file? We don't seem to be using that anywhere.

**Review by kkovaacs — APPROVED** [review]
LGTM for now, we can fix this up properly later.

**Comment by CHr15F0x** [comment]
>Slightly unrelated question: why do we need the .d file? We don't seem to be using that anywhere.
No idea :eyes:

**Comment by Mirko-von-Leipzig** [comment]
> Slightly unrelated question: why do we need the `.d` file? We don't seem to be using that anywhere.

Probably just me thinking we needed it.

**Pull request merged**
